# ===============================
# secrets_template.toml
# ===============================
# 📌 Copy this file to 'secrets.toml'
# 📌 Fill in your real keys & secrets

[api_keys]
# 👉 Replace with your actual OpenAI API key
OPENROUTER_API_KEY="YOUR_API_KEY_HERE"

# ===============================

